trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: rubrica-web-app-vars

stages:
  - stage: Test
    jobs:
      - job: TestVariables
        steps:
          - script: |
              echo "Testing variable access..."
              echo "APP_SERVICE_NAME: $(APP_SERVICE_NAME)"
              echo "AZURE_REGION: $(AZURE_REGION)"
              echo "RESOURCE_GROUP: $(RESOURCE_GROUP)"
            displayName: 'Debug Variables'
  
  - stage: Infrastructure
    jobs:
      - job: Terraform
        steps:
          - task: TerraformInstaller@0
            inputs:
              terraformVersion: '1.9.8'
          
          - task: TerraformTaskV3@3
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)'
          
          - task: TerraformTaskV3@3
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: '$(AZURE_SUBSCRIPTION)'
              workingDirectory: '$(System.DefaultWorkingDirectory)'
