trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: rubrica-web-app-vars

steps:
  - task: TerraformInstaller@0
    displayName: 'Install Terraform'
    inputs:
      terraformVersion: '1.9.8'

  - task: TerraformCLI@0
    displayName: 'Terraform Init'
    inputs:
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      backendType: 'azurerm'
      backendServiceArm: '$(AZURE_SUBSCRIPTION)'
      ensureBackend: true
      backendAzureRmResourceGroupName: '$(RESOURCE_GROUP)'
      backendAzureRmStorageAccountName: 'storubricabackend'
      backendAzureRmContainerName: 'tfstate'
      backendAzureRmKey: 'terraform.tfstate'

  - task: TerraformCLI@0
    displayName: 'Terraform Plan'
    inputs:
      command: 'plan'
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      environmentServiceName: '$(AZURE_SUBSCRIPTION)'
      publishPlanResults: 'Rubrica-Plan'

  - task: TerraformCLI@0
    displayName: 'Terraform Apply'
    inputs:
      command: 'apply'
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      environmentServiceName: '$(AZURE_SUBSCRIPTION)'